# Generated by Django 5.1.1 on 2025-08-06 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('idField', models.AutoField(primary_key=True, serialize=False)),
                ('NameField', models.CharField(max_length=100, unique=True)),
                ('Description', models.TextField(blank=True, null=True)),
                ('isActive', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'field',
                'verbose_name_plural': 'fields',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('idLanguage', models.AutoField(primary_key=True, serialize=False)),
                ('Language', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'language',
                'verbose_name_plural': 'languages',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('idSchool', models.AutoField(primary_key=True, serialize=False)),
                ('NameSchool', models.CharField(max_length=100, unique=True)),
                ('CodeSchool', models.IntegerField(unique=True)),
                ('isActive', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'school',
                'verbose_name_plural': 'schools',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('idSection', models.AutoField(primary_key=True, serialize=False)),
                ('NameSection', models.CharField(max_length=100, unique=True)),
                ('LetterSection', models.CharField(max_length=5, unique=True)),
                ('isActive', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'section',
                'verbose_name_plural': 'sections',
            },
        ),
        migrations.CreateModel(
            name='TypeProfessor',
            fields=[
                ('idTypeProfessor', models.AutoField(primary_key=True, serialize=False)),
                ('NameContract', models.CharField(max_length=100)),
                ('isFullTime', models.BooleanField(default=False)),
                ('isPermanent', models.BooleanField(default=False)),
                ('Comment', models.TextField(blank=True, null=True)),
                ('isActive', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'type of professor',
                'verbose_name_plural': 'types of professors',
            },
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('idYear', models.AutoField(primary_key=True, serialize=False)),
                ('Year', models.CharField(max_length=9, unique=True)),
                ('isEditable', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'year',
                'verbose_name_plural': 'years',
            },
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('idDegree', models.AutoField(primary_key=True, serialize=False)),
                ('NameDegree', models.CharField(max_length=100)),
                ('CodeDegree', models.IntegerField(unique=True)),
                ('isActive', models.BooleanField(default=True)),
                ('School', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AcademicInfoApp.school')),
            ],
            options={
                'verbose_name': 'degree',
                'verbose_name_plural': 'degrees',
                'unique_together': {('NameDegree', 'School')},
            },
        ),
        migrations.AddField(
            model_name='school',
            name='Section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AcademicInfoApp.section'),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('idCourse', models.AutoField(primary_key=True, serialize=False)),
                ('NameCourse', models.CharField(max_length=100)),
                ('CodeCourse', models.IntegerField(unique=True)),
                ('ECTS', models.DecimalField(decimal_places=2, max_digits=5)),
                ('isActive', models.BooleanField(default=True)),
                ('Degree', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AcademicInfoApp.degree')),
                ('Field', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AcademicInfoApp.field')),
            ],
            options={
                'verbose_name': 'course',
                'verbose_name_plural': 'courses',
                'unique_together': {('NameCourse', 'Degree')},
            },
        ),
    ]
