# Generated by Django 5.1.1 on 2025-08-06 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AcademicInfoApp', '0001_initial'),
        ('UsersApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Free',
            fields=[
                ('idFree', models.AutoField(primary_key=True, serialize=False)),
                ('PointsFree', models.IntegerField(default=0)),
                ('Comment', models.TextField(blank=True, null=True)),
                ('Professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UsersApp.professor')),
                ('Year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AcademicInfoApp.year')),
            ],
            options={
                'verbose_name': 'free',
                'verbose_name_plural': 'frees',
            },
        ),
        migrations.CreateModel(
            name='Capacity',
            fields=[
                ('idCapacity', models.AutoField(primary_key=True, serialize=False)),
                ('Points', models.IntegerField(default=0)),
                ('Comment', models.TextField(blank=True, null=True)),
                ('Professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UsersApp.professor')),
                ('Year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AcademicInfoApp.year')),
            ],
            options={
                'verbose_name': 'capacity',
                'verbose_name_plural': 'capacities',
                'unique_together': {('Professor', 'Year')},
            },
        ),
        migrations.CreateModel(
            name='CapacitySection',
            fields=[
                ('idCapacitySection', models.AutoField(primary_key=True, serialize=False)),
                ('Points', models.IntegerField(default=0)),
                ('Comment', models.TextField(blank=True, null=True)),
                ('Professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UsersApp.professor')),
                ('Section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AcademicInfoApp.section')),
                ('Year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AcademicInfoApp.year')),
            ],
            options={
                'verbose_name': 'capacity section',
                'verbose_name_plural': 'capacity sections',
                'unique_together': {('Professor', 'Year', 'Section')},
            },
        ),
        migrations.CreateModel(
            name='CourseYear',
            fields=[
                ('idCourseYear', models.AutoField(primary_key=True, serialize=False)),
                ('Semester', models.CharField(choices=[('Q1', 'Q1'), ('Q2', 'Q2')], default='Q1', max_length=2)),
                ('PointsA', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('PointsB', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('PointsC', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('PointsD', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('PointsE', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('PointsF', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('Comment', models.TextField(blank=True, null=True)),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_years', to='AcademicInfoApp.course')),
                ('Language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_years', to='AcademicInfoApp.language')),
                ('Year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_years', to='AcademicInfoApp.year')),
            ],
            options={
                'verbose_name': 'course year',
                'verbose_name_plural': 'course years',
                'unique_together': {('Year', 'Course', 'Semester')},
            },
        ),
        migrations.CreateModel(
            name='TypePoints',
            fields=[
                ('idTypePoints', models.AutoField(primary_key=True, serialize=False)),
                ('NamePointsA', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('NamePointsB', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('NamePointsC', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('NamePointsD', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('NamePointsE', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('NamePointsF', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('Section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AcademicInfoApp.section')),
                ('Year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AcademicInfoApp.year')),
            ],
            options={
                'verbose_name': 'type points',
                'verbose_name_plural': 'type points',
                'unique_together': {('Year', 'Section')},
            },
        ),
    ]
