# Generated by Django 5.1.1 on 2025-08-06 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ProfSectionCapacityApp', '0001_initial'),
        ('UsersApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('idAssignment', models.AutoField(primary_key=True, serialize=False)),
                ('PointsA', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('PointsB', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('PointsC', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('PointsD', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('PointsE', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('PointsF', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('isCoordinator', models.BooleanField(default=False)),
                ('CourseYear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProfSectionCapacityApp.courseyear')),
                ('Professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UsersApp.professor')),
            ],
            options={
                'verbose_name': 'assignment',
                'verbose_name_plural': 'assignments',
                'unique_together': {('Professor', 'CourseYear')},
            },
        ),
    ]
